NDefines.NMilitary.BASE_MP_TO_MANPOWER = 0.2
NDefines.NMilitary.SIEGE_ATTRITION = 1.5					-- (was 1)
NDefines.NMilitary.SIEGE_DISEASE_IMPACT = 0.1				-- Fraction of besieging soldiers lost in a disease outbraek (was .05)
NDefines.NMilitary.ARMY_DRILL_YEARLY_DECAY = -1.0			-- Loss from not Drilling (was 2.5)
NDefines.MAX_SAILOR_LACK_ATTRITION = 0.75				-- (was 1)
NDefines.NMilitary.HEAVY_SHIP_SAILORS_COST = 400			-- 1 = 1000 men in cost. (was 200)
NDefines.NMilitary.LIGHT_SHIP_SAILORS_COST = 75			-- 1 = 1000 men in cost. (was 50)
NDefines.NMilitary.GALLEY_SHIP_SAILORS_COST = 150			-- 1 = 1000 men in cost. (was 100)
NDefines.NMilitary.TRANSPORT_SHIP_SAILORS_COST = 75			-- 1 = 1000 men in cost. (was 50)
NDefines.NMilitary.HEAVY_SHIP_COST = 100 						-- _MDEF_HEAVY_SHIP_COST = 10	 (was 50)
NDefines.NMilitary.LIGHT_SHIP_COST = 30 						-- _MDEF_LIGHT_SHIP_COST = 10	 (was 20)
NDefines.NMilitary.GALLEY_COST = 14 							-- _MDEF_GALLEY_COST = 10	 (was 12)
NDefines.NMilitary.TRANSPORT_COST = 16							-- _MDEF_TRANSPORT_COST = 10	 (was 12)
NDefines.NMilitary.HEAVY_SHIP_TIME = 730 						-- _MDEF_HEAVY_SHIP_TIME = 10	 (was 730)
NDefines.NMilitary.LIGHT_SHIP_TIME = 545 						-- _MDEF_LIGHT_SHIP_TIME = 10	 (was 365)
NDefines.NMilitary.GALLEY_TIME = 365 							-- _MDEF_GALLEY_TIME = 10	 (was 365)
NDefines.NMilitary.TRANSPORT_TIME = 365 						-- _MDEF_TRANSPORT_TIME = 10	 (was 365)
NDefines.NMilitary.MONTHLY_REPAIR = 0.05						-- Ship repair speed.	 	 (was .1)
NDefines.NMilitary.FLAGSHIP_COST_DUCATS = 200						-- The cost in ducats of a flagship (was 100)
NDefines.NMilitary.FLAGSHIP_COST_SAILORS = 500						-- The cost in sailors of a flagship (was 300)
NDefines.NMilitary.PARTICIPATION_SCORE_BLOCKADE = 0.003