NDefines.NAI.PEACE_DESIRE_AI_PREFS_QUICK_PEACE = 50
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 16
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 120
--
NDefines.NAI.ASSIMILATION_INTEREST_AMOUNT_FACTOR = 200.0
NDefines.NAI.ARMY_DISTANCE_SCORE_IMPACT	= 1.05
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 8.5
NDefines.NAI.PURSUE_DISTANCE = 95
--
NDefines.NAI.REGION_PLANNING_HOMELAND_PRIORIZATION = 7.5
NDefines.NAI.MIN_FORCE_LIMIT_SHARE_REGION_ASSIGN = 0.2
NDefines.NAI.MAX_TASKS_NEW_REGION_ASSIGN_ALGORITHM = 100
NDefines.NAI.MAX_ARMIES_NEW_REGION_ASSIGN_ALGORITHM = 80
--
NDefines.NAI.TRANSPORT_FRACTION = 0.3
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 30
NDefines.NAI.ARTILLERY_FRACTION = 0.35
NDefines.NAI.ONLY_INFANTRY_MERCS = 0
--
NDefines.NAI.IMPORTANT_PROVINCE_THRESHOLD = 0.03
--
