NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 50.0
NDefines.NAI.MAX_SAVINGS = 150.0
NDefines.NAI.EXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0.2
--
NDefines.NAI.ADVISOR_BUDGET_FRACTION = 0.415
NDefines.NAI.RECRUIT_ADVISOR_BASE_AI_DESIRE = 80.0
NDefines.NAI.PROMOTE_ADVISOR_BASE_AI_DESIRE = 40.0
--
NDefines.NAI.COLONY_BUDGET_FRACTION = 0.2
NDefines.NAI.ARMY_BUDGET_FRACTION = 1.0
NDefines.NAI.NAVY_BUDGET_FRACTION = 0.5
NDefines.NAI.FORT_BUDGET_FRACTION = 0.5
--
NDefines.NAI.UPGRADE_CENTER_OF_TRADE_BASE_AI_DESIRE = 75.0
--