NDefines.NAI.PS_SHORT_TERM_POOL = 250.0
--
NDefines.NAI.ESTATE_MAX_WANTED_INFLUENCE = 85.0
NDefines.NAI.ESTATE_MIN_WANTED_CROWNLAND = 20.0
--
NDefines.NAI.EDICT_VALUE_THRESHOLD = 50
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_DEFICIT = 15
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_LOW_INCOME = 2
--
NDefines.NAI.AI_TOTAL_DEV_CULTURE_MULTIPLIER = 10